### ISSUE TITLE
Title not set in template parameters when editing person

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#142]
1.  Display all persons.
2.  Pick a person.
3.  Edit (e.g., go to http://127.0.0.1:8000/workshops/person/100/edit).
4.  View source.

If you have #140, you will see XXX-unset-variable-XXX as the page title, because `title` isn't included in the context used when the page is expanded.  How should `title` be set when editing?  The editing form is auto-generated from `PersonUpdate(UpdateView)`.

**Comment by pbanaszkiewicz** [comment]
Hey, @gvwilson, I don't have much experience with class-based views, but it seems like `ContextMixin` is a solution:
https://docs.djangoproject.com/en/1.7/topics/class-based-views/mixins/#context-and-template-responses

Here's sample usage:
https://docs.djangoproject.com/en/1.7/ref/class-based-views/mixins-simple/#django.views.generic.base.ContextMixin.get_context_data

We can basically inherit `ContextMixin` as, for example, `UpdateViewContextMixin` that provides proper title:
```python
class UpdateViewContext(UpdateView, ContextMixin):
    def get_context_data(self, **kwargs):
        context = super(ContextMixin, self).get_context_data(**kwargs)
        context['title'] = str(self.object)  # from UpdateView
        return context
```

Then we can use `UpdateViewContext` instead of `UpdateView`, I think.

**Comment by gvwilson** [comment]
Hi Piotr,
Doesn't work for me.  Grab #143 (which isolates this change), and look at:

~~~
class PersonUpdate(UpdateView, ContextMixin):
     model = Person
     fields = '__all__'
     pk_url_kwarg = 'person_id'

     def get_context_data(self, **kwargs):
         context = super(UpdateView, self).get_context_data(**kwargs)
         context['title'] = str(self.object)
         return context
~~~

The title is still 'XXX-unset-variable-XXX.  If I change the `super` 
call to `super(ContextMixin, self)`, Python complains that there's no 
such method.

**Comment by pbanaszkiewicz** [comment]
Greg, it's definitely working for me:
![screenshot from 2015-01-16 15 02 15](https://cloud.githubusercontent.com/assets/72821/5777234/b4a8b222-9d90-11e4-9e46-2622d0a9ca0c.png)

What are your Python and Django versions? I'm using:

```
Python 2.7.9 :: Continuum Analytics, Inc.
Django 1.7.1
```

I believe you should invoke `super()` in this way:
```python
    def get_context_data(self, **kwargs):
        context = super(PersonUpdate, self).get_context_data(**kwargs)
        context['title'] = str(self.object)  # from UpdateView
        return context
```

The change is that in your code you had `super(UpdateView, self)`, here it's `super(PersonUpdate, self)`.

I'm still advocating for using a new class-based view that I wrote in previous post (there's an error linked to using `super()` that I fixed in code below):

```python
class UpdateViewContext(UpdateView, ContextMixin):
    def get_context_data(self, **kwargs):
        context = super(UpdateViewContext, self).get_context_data(**kwargs)
        context['title'] = str(self.object)
        return context
```

I tried this and it worked. Cheers!

**Comment by gvwilson** [comment]
Hi Piotr,
Can you submit a PR with your version and I'll try it here?
Thanks,
Greg

**Comment by gvwilson** [comment]
Python 2.7.8 |Anaconda 2.1.0 and django.VERSION = (1, 7, 1, 'final', 0)

And I tried both the `super(PersonUpdate, self)` and the 
UpdateViewContext that you advocated - failed the same way.

**Comment by pbanaszkiewicz** [comment]
Greg, I sent you https://github.com/gvwilson/amy/pull/11.

**Comment by gvwilson** [comment]
Yup, I replied - fixes the title, but breadcrumbs are still not set.  
Separate bug?

**Comment by pbanaszkiewicz** [comment]
Greg,
yeah there are some minor bugs with breadcrumbs. I'd go ahead and merge this PR and let me squash these bugs.
Cheers

**Comment by gvwilson** [comment]
Thanks - I fixed some things in the adding-tests branch (in particular, 
escaping characters in breadcrumb text), so you might want to start from 
there.  I'll go ahead and merge in your title-fixing PR.
Thanks,
Greg

**Comment by gvwilson** [comment]
p.s. should UpdateViewContext be used as a parent for all other editing 
views?  And is something equivalent needed for the creation views?

**Comment by pbanaszkiewicz** [comment]
1) Yes, unless we have to use some specific template variables other than `title`. In that case, we should directly inherit `ContextMixin`
2) Yes, I can see some `XXX-unset-variable-XXX` in title when creating a new person.

**Comment by gvwilson** [comment]
Thanks - can you please update the ones that need updating? I think 
`title` will be enough, and I'm building tests to catch other cases that 
might slip through.
Thanks,
Greg
